project_id = "dmgjatzisypbddvlfzbz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
sender_name = "Supabase"
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
s3_host = "127.0.0.1"
s3_port = 54327
s3_protocol = "http"
s3_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
s3_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aedad99ced5eae08f3"
s3_region = "local"
global_s3_bucket = "supa-emulator-storage"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_confirm = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_email = true
enable_confirmations = false
template_subjects_net_new_login = "Please confirm your email"
template_subjects_magic_link = "Your Magic Link"
template_subjects_email_change = "Please confirm your email change"
template_subjects_recovery = "Reset Your Password"

[auth.sms]
enable_signup = false
enable_confirmations = false
template_body_sms_login = "Your code is {{ .Code }}"
template_body_sms_signup = "Your code is {{ .Code }}"

[functions.send-ticket-sms]
verify_jwt = false

[functions.verify-ticket]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54328